# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171002_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.PositiveIntegerField(default=1, verbose_name='阅读量'),
        ),
    ]
